#!/bin/bash
php bin/doctrine orm:schema-tool:update --complete --dump-sql
echo -n "Proceed? [Y/n]: "
read -r

if [[ $REPLY == "y" || $REPLY == "Y" ]]; then
  php bin/doctrine orm:schema-tool:update --complete --force
fi